name: build
on: push
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12]
        exclude:
          - os: macos-latest
            node-version: 12.x
    steps:
      - name: my first step 
        env:
          MY_VAR: "Hello! My name is" 
          FIRST_NAME: Xcho
          LAST_NAME: Avagyan
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME
      - name: my second job
        if: success()
        run: echo "The step finnished"
